#############################################################################
# Makefile for building: Pilorama.app/Contents/MacOS/Pilorama
# Generated by qmake (3.1) (Qt 5.15.1)
# Project:  ../src/pilorama.pro
# Template: app
# Command: /usr/local/opt/qt/bin/qmake -o Pilorama.xcodeproj/project.pbxproj ../src/pilorama.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /usr/local/opt/qt/bin/qmake
Pilorama.xcodeproj/project.pbxproj: ../src/pilorama.pro /usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/macx-xcode/qmake.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/lex.prf \
		../src/pilorama.pro \
		../src/qml.qrc \
		/usr/local/Cellar/qt/5.15.1/lib/QtQuick.framework/Resources/QtQuick.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtSvg.framework/Resources/QtSvg.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtQmlModels.framework/Resources/QtQmlModels.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtQml.framework/Resources/QtQml.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtXml.framework/Resources/QtXml.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Pilorama.xcodeproj/project.pbxproj ../src/pilorama.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/macx-xcode/qmake.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_post.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources_functions.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/lex.prf:
../src/pilorama.pro:
../src/qml.qrc:
/usr/local/Cellar/qt/5.15.1/lib/QtQuick.framework/Resources/QtQuick.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtSvg.framework/Resources/QtSvg.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtQmlModels.framework/Resources/QtQmlModels.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtQml.framework/Resources/QtQml.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtNetwork.framework/Resources/QtNetwork.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtXml.framework/Resources/QtXml.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Pilorama.xcodeproj/project.pbxproj ../src/pilorama.pro -spec macx-xcode

qmake_all: FORCE

