name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Dependencies
      run: |
        brew install qt
    - name: Build Application
      run: |
        qmake src/pilorama.pro
        make
