name: GitHub Actions

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Pre-build Packages
    runs-on: macos-10.15
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Dependencies
      run: |
        brew install qt
        export PATH="/usr/local/opt/qt/bin:$PATH"
        ls /usr/local/opt/qt/bin
    - name: Build Application
      run: |
        qmake src/pilorama.pro
        make
