name: GitHub Actions

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Pre-build Packages
    runs-on: macos-10.15
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Dependencies
      run: |
        brew install qt
    - name: Build Application
      run: |
        /usr/local/opt/qt/bin/qmake -config release src/pilorama.pro
        make
    - name: Prepare Build
      run: |
        mkdir executable
        mv pilorama.app executable/pilorama.app
    - name: Store Application
      uses: actions/upload-artifact@v2
      with:
        name: pilorama.app
        path: executable
