name: Test Buildability

on:
  pull_request:
    types: [ready_for_review]
    branches:
      - master

jobs:
  macos:
    name: Test MacOS Buildability
    runs-on: macos-14
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: "6.9.1"
        modules: qtmultimedia
        cache: true
        cache-key-prefix: ${{ runner.os }}-QtCache-6_9_1

    - name: Build Application
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ../src
        make

    - name: Run Application Headlessly
      run: |
        set -e
        export QT_QPA_PLATFORM=offscreen
        ./build/Pilorama.app/Contents/MacOS/Pilorama &
        PID=$!
        sleep 5
        if kill -0 $PID 2>/dev/null; then
          kill $PID
          wait $PID || true
        else
          wait $PID
          CODE=$?
          if [ "$CODE" -ne 0 ]; then
            echo "Application exited early with code $CODE"
            exit $CODE
          fi
        fi

  windows:
    name: Test Windows Buildability
    runs-on: windows-2022
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.1'
        modules: qtmultimedia
        cache: true
        cache-key-prefix: ${{ runner.os }}-QtCache-6_9_1
    - name: Setup Additional Dependencies
      shell: cmd
      run: |
        choco install cmake
    - name: Build Application
      shell: cmd
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ../src
        cmake --build . --config Release

    - name: Run Application Headlessly
      shell: pwsh
      run: |
        $env:QT_QPA_PLATFORM="offscreen"
        $process = Start-Process -FilePath "build\Release\Pilorama.exe" -PassThru -WindowStyle Hidden
        Start-Sleep -Seconds 5
        if ($process.HasExited) {
            if ($process.ExitCode -ne 0) { exit $process.ExitCode }
        } else {
            Stop-Process -Id $process.Id
        }

  linux:
    name: Test Linux Buildability
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.9.1"
          modules: qtmultimedia
          cache: true
          cache-key-prefix: ${{ runner.os }}-QtCache-6_9_1

      - name: Build Application
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ../src
          cmake --build . --config Release

      - name: Run Application Headlessly
        run: |
          set -e
          export QT_QPA_PLATFORM=offscreen
          ./build/Pilorama &
          PID=$!
          sleep 5
          if kill -0 $PID 2>/dev/null; then
            kill $PID
            wait $PID || true
          else
            wait $PID
            CODE=$?
            if [ "$CODE" -ne 0 ]; then
              echo "Application exited early with code $CODE"
              exit $CODE
            fi
          fi
