name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  macos:
    name: Pre-build MacOS Package
    runs-on: macos-14
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'
        cache: true
        cache-key-prefix: ${{ runner.os }}-QtCache-6_7_2
    - name: Setup Additional Dependencies
      run: |
        brew install create-dmg cmake
    - name: Build Application
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ../src
        make
        macdeployqt Pilorama -qmldir=../src
    - name: Make Installer
      run: |
        mkdir executable
        mv build/Pilorama.app executable/Pilorama.app
        create-dmg --volname Pilorama --background assets/background.png --window-size 540 320 --icon Pilorama.app 128 128 --app-drop-link 384 128 --no-internet-enable Pilorama.dmg executable/
    - name: Store Package
      uses: actions/upload-artifact@v4
      with:
        name: Pilorama.dmg
        path: Pilorama.dmg
  windows:
    name: Pre-build Windows Package
    runs-on: windows-2022
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'
        cache: true
        cache-key-prefix: ${{ runner.os }}-QtCache-6_7_2
    - name: Setup Additional Dependencies
      shell: cmd
      run: |
        choco install cmake
    - name: Build Application
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ../src
        cmake --build . --config Release
        windeployqt release\Pilorama.exe -qmldir=../src
    - name: Make Installer
      shell: cmd
      run: |
        iscc wndws.iss
    - name: Store Package
      uses: actions/upload-artifact@v4
      with:
        name: Pilorama_Setup.exe
        path: Pilorama_Setup.exe
