name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  macos:
    name: Pre-build MacOS Package
    runs-on: macos-10.15
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Dependencies
      run: |
        brew install qt
        brew install create-dmg
        bundle install
    - name: Build Application
      run: |
        /usr/local/opt/qt/bin/qmake -config release src/pilorama.pro
        make
        /usr/local/opt/qt/bin/macdeployqt Pilorama.app -qmldir=./src
    - name: Fetch Certificate
      env:
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      run: |
        bundle exec fastlane ios certificates
    - name: Codesign
      run: |
        codesign \
         --sign "Developer ID Application: SIGONNA LLC (BF7ZL72794)" \
         --timestamp \
         --options runtime \
         --force \
         --deep \
         Pilorama.app
    - name: Notarize Application
      env:
        ICLOUD_USER: ${{ secrets.ICLOUD_USER }}
        ICLOUD_PASSWORD: ${{ secrets.ICLOUD_PASSWORD }}
      run: |
        ditto -c -k --keepParent Pilorama.app Pilorama.zip
        xcrun altool \
         --notarize-app \
         --primary-bundle-id "com.sigonna.opensource.Pilorama" \
         -u "$ICLOUD_USER" -p "$ICLOUD_PASSWORD" \
         --file Pilorama.zip
    - name: Make Installer
      run: |
        mkdir executable
        mv Pilorama.app executable/Pilorama.app
        create-dmg --volname Pilorama --background assets/background.png --window-size 540 320 --icon Pilorama.app 128 128 --app-drop-link 384 128 --no-internet-enable Pilorama.dmg executable/
    - name: Store Package
      uses: actions/upload-artifact@v2
      with:
        name: Pilorama.dmg
        path: Pilorama.dmg
  windows:
    name: Pre-build Windows Package
    runs-on: windows-2019
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Dependencies
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.0'
    - name: Build Application
      shell: cmd
      run: |
        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        qmake -config release src\pilorama.pro
        nmake
        windeployqt release/Pilorama.exe -qmldir=./src
    - name: Make Installer
      shell: cmd
      run: |
        iscc wndws.iss
    - name: Store Package
      uses: actions/upload-artifact@v2
      with:
        name: Pilorama_Setup.exe
        path: Pilorama_Setup.exe
