name: Pre-Release

on:
  create:
    tags:
      - 'v*.*.*'

jobs:
  macos:
    name: Pre-build MacOS Package
    runs-on: macos-10.15
    steps:
    - name: Setup Dependencies
      run: |
        brew install qt
        brew install create-dmg
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set Version
      run: |
        export VERSION=${GITHUB_REF##*v}
        sed -i '' 's/Version=[0-9]*\.[0-9]*\.[0-9]*/Version='"$VERSION"'/g' src/pilorama.desktop
        sed -i '' 's/VERSION=[0-9]*\.[0-9]*\.[0-9]*/VERSION='"$VERSION"'/g' src/pilorama.pro
    - name: Build Application
      run: |
        /usr/local/opt/qt/bin/qmake -config release src/pilorama.pro
        make
        /usr/local/opt/qt/bin/macdeployqt Pilorama.app -qmldir=./src
    - name: Make Installer
      run: |
        mkdir executable
        mv Pilorama.app executable/Pilorama.app
        create-dmg --volname Pilorama --background assets/background.png --window-size 540 320 --icon Pilorama.app 128 128 --app-drop-link 384 128 --no-internet-enable Pilorama.dmg executable/
    - name: Store Application
      uses: actions/upload-artifact@v2
      with:
        name: Pilorama.dmg
        path: Pilorama.dmg
  windows:
    name: Pre-build Windows Package
    runs-on: windows-2019
    steps:
    - name: Setup Dependencies
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.0'
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set Version
      shell: bash
      run: |
        export VERSION=${GITHUB_REF##*v}
        sed -i 's/Version=[0-9]*\.[0-9]*\.[0-9]*/Version='"$VERSION"'/g' src/pilorama.desktop
        sed -i 's/#define MyAppVersion "[0-9]*\.[0-9]*\.[0-9]"/#define MyAppVersion "'"$VERSION"'"/g' wndws.iss
        sed -i 's/VERSION=[0-9]*\.[0-9]*\.[0-9]*/VERSION='"$VERSION"'/g' src/pilorama.pro
    - name: Build Application
      shell: cmd
      run: |
        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        qmake -config release src\pilorama.pro
        nmake
        windeployqt release/Pilorama.exe -qmldir=./src
    - name: Make Installer
      shell: cmd
      run: |
        iscc wndws.iss
    - name: Store Application
      uses: actions/upload-artifact@v2
      with:
        name: Pilorama_Setup.exe
        path: Pilorama_Setup.exe
  push_back:
    name: Send published version to HEAD
    runs-on: ubuntu-20.04
    needs: [macos, windows]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set Version
      run: |
        export VERSION=${GITHUB_REF##*v}
        sed -i 's/Version=[0-9]*\.[0-9]*\.[0-9]*/Version='"$VERSION"'/g' src/pilorama.desktop
        sed -i 's/#define MyAppVersion "[0-9]*\.[0-9]*\.[0-9]*"/#define MyAppVersion "'"$VERSION"'"/g' wndws.iss
        sed -i 's/VERSION=[0-9]*\.[0-9]*\.[0-9]*/VERSION='"$VERSION"'/g' src/pilorama.pro
    - name: Commit Version
      run: |
        export VERSION=${GITHUB_REF##*v}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Release version $VERSION" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
